GET http://localhost:5000/auth/users

###

POST http://localhost:5000/auth/registration
Content-Type: application/json

{
  "username": "Andrew",
  "password": "tartilik1"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "Dan",
  "password": "tartilik1"
}
