GET http://localhost:5000/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODZmYjdiYjE1MzBlNTU5MjliNDQ1YSIsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTcyMDEyNDU2OCwiZXhwIjoxNzIwMjEwOTY4fQ.Y757nnkovFbS_OykPsa9Pm3qSBJkAzeSRSQT09noZC0
###

POST http://localhost:5000/auth/registration
Content-Type: application/json

{
  "username": "Andrew",
  "password": "tartilik1"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
